# Generated by Django 2.0 on 2019-10-08 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user_model',
        ),
    ]
