# Generated by Django 2.0 on 2019-09-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190924_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='tag_set',
            field=models.ManyToManyField(related_name='articles', to='article.Tag'),
        ),
    ]
