# Generated by Django 2.0 on 2019-10-10 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('view_article', '查看文章的权限')]},
        ),
    ]
