# Generated by Django 2.0 on 2019-09-30 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('1[3-9]\\d{9}')])),
            ],
        ),
    ]
